### ISSUE TITLE
Authentication suddenly not working

### ISSUE THREAD

**Issue by mobinni** [theoephraim/grunt-i18n-gspreadsheet#12]
I ran my project today and it keeps saying my credentials are wrong, yet they are not.
When I place the spreadsheet public it still says it's private.

**Comment by mobinni** [comment]
Found a temporary fix, publish your spreadsheet and set it only to be found with people with the link. This way you can still build your project without auth

**Comment by lakefield** [comment]
This just started happening for me as well. 

Warning: Running "i18n_gspreadsheet:config" (i18n_gspreadsheet) task
Invalid google credentials for [redacted]

**Comment by lakefield** [comment]
Ah, so looks like Google made a breaking change and the auth method will need to be updated:

https://github.com/theoephraim/node-google-spreadsheet/issues/38

**Comment by mobinni** [comment]
I don't think this issue will be fixed.

**Comment by jonathandion** [comment]
Any solution?
